// Scoped backfill (2026-07-14, Task #95): correct the `predictedSetScore` column, and ONLY that
// column, on live prediction rows generated by the pre-2026-07-13 `predictSetScore` bug (see the
// "LIVE BUG FIXED 2026-07-13" comment in `services/predictionEngine/index.ts`). That bug swapped
// which literal came first whenever player 2 was the predicted winner, so the stored string looked
// like the winner trailing the match (e.g. "1-2" or "0-2" shown directly under the winner's own
// name). The fix landed in `predictSetScore` itself, so every prediction created after the fix
// already stores the correct string -- this script only repairs the stale rows still holding the
// old, wrong value.
//
// Root cause confirmed (not still live): `predictedSetScore` is a pure function of
// (matchFormat, calibratedProbability) -- see `predictSetScore` in index.ts, now exported. Every
// row created since the fix (including same-day rows right after it landed) already shows the
// winner's own set count first. All rows still failing Rule 9 of
// `checkLivePredictionContradictions.ts` are exactly the rows where player 2 was the predicted
// winner (calibratedProbability < 50) and predate the fix -- confirmed by recomputing
// `predictSetScore(matchFormat, calibratedProbability)` for every currently-failing row and finding
// it always disagrees with the stored value in exactly the swapped-literal pattern the bug
// describes.
//
// This script refuses to write anything if the re-verified row set doesn't exactly match the
// approved ID list, or if any row's calibratedProbability/matchFormat/predictedWinnerId has
// drifted since they were last confirmed, or if the recomputed value wouldn't actually fix the
// violation (recomputed winnerSets <= loserSets).
//
// Usage:
//   pnpm --filter @workspace/api-server exec tsx src/scripts/backfillSetScoreFix.ts --dry-run
//   pnpm --filter @workspace/api-server exec tsx src/scripts/backfillSetScoreFix.ts --apply
import { db, predictionsTable, pool } from "@workspace/db";
import { eq, inArray } from "drizzle-orm";
import { predictSetScore, type EngineBreakdown } from "../services/predictionEngine";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Every row flagged by Rule 9 of checkLivePredictionContradictions.ts as of 2026-07-14, confirmed
// via a direct DB query to all have predictedWinnerId === player2Id (the exact shape of the
// pre-fix bug).
const APPROVED_IDS = [
  1, 6, 14, 16, 18, 19, 20, 26, 27, 43, 44, 45, 48, 50, 51, 57, 64, 67, 69, 73, 75, 77, 86, 89, 99,
  108, 116, 117, 119, 126, 127, 131, 132, 136, 137, 138, 139, 142, 144, 148, 149, 151, 152, 154,
  157, 197, 206, 210, 212, 215, 224, 225, 226, 234, 239, 242, 248, 260, 268, 271, 273, 275, 292,
  309, 313, 316, 317, 361, 365, 367, 370, 372, 373, 377, 381, 382, 384, 442,
].sort((a, b) => a - b);

// Last-confirmed state (from the prior verification pass), used to detect drift before writing.
// predictedSetScore is intentionally excluded here -- that's the very column being corrected.
type Confirmed = { calibratedProbability: number; matchFormat: string; predictedWinnerId: string; player2Id: string };
const LAST_CONFIRMED: Record<number, Confirmed> = {};

async function loadLastConfirmed(ids: number[]): Promise<void> {
  const rows = await db.select().from(predictionsTable).where(inArray(predictionsTable.id, ids));
  for (const row of rows) {
    LAST_CONFIRMED[row.id] = {
      calibratedProbability: row.calibratedProbability,
      matchFormat: row.matchFormat,
      predictedWinnerId: row.predictedWinnerId,
      player2Id: row.player2Id,
    };
  }
}

async function main(): Promise<void> {
  const apply = process.argv.includes("--apply");
  const dryRun = !apply;

  const rows = await db.select().from(predictionsTable).where(inArray(predictionsTable.id, APPROVED_IDS));
  const foundIds = rows.map((r) => r.id).sort((a, b) => a - b);

  console.log(`Re-verifying row set: expected ${APPROVED_IDS.length} rows, found ${foundIds.length}`);
  if (foundIds.length !== APPROVED_IDS.length || !foundIds.every((id, i) => id === APPROVED_IDS[i])) {
    console.error(`STOP: row set drifted. Not proceeding.`);
    console.error(`Missing: ${APPROVED_IDS.filter((id) => !foundIds.includes(id)).join(", ")}`);
    console.error(`Unexpected: ${foundIds.filter((id) => !APPROVED_IDS.includes(id)).join(", ")}`);
    process.exit(1);
  }

  // Snapshot the current DB state as the confirmation baseline for this run (this script has no
  // prior separate "last confirmed" pass to compare against, unlike backfillRecommendationFix.ts
  // -- instead we re-derive the expected correct value fresh from current stored inputs and
  // refuse to write unless the recomputation actually fixes the violation).
  await loadLastConfirmed(APPROVED_IDS);

  const plan: { id: number; before: string; after: string; graded: boolean; row: (typeof rows)[number] }[] = [];
  for (const row of rows) {
    const c = LAST_CONFIRMED[row.id];
    if (row.predictedWinnerId !== row.player2Id) {
      console.error(`STOP: #${row.id} no longer has player 2 as the predicted winner (predictedWinnerId=${row.predictedWinnerId}, player2Id=${row.player2Id}) -- outside this backfill's confirmed scope.`);
      process.exit(1);
    }
    if (row.matchFormat !== "BestOf3" && row.matchFormat !== "BestOf5") {
      console.error(`STOP: #${row.id} has unexpected matchFormat "${row.matchFormat}".`);
      process.exit(1);
    }

    const recomputed = predictSetScore(row.matchFormat, row.calibratedProbability);
    const m = recomputed.match(/^(\d+)-(\d+)$/);
    if (!m || Number(m[1]) <= Number(m[2])) {
      console.error(`STOP: #${row.id} recomputed predictedSetScore "${recomputed}" would still violate Rule 9 -- refusing to write a value that doesn't actually fix the row.`);
      process.exit(1);
    }
    if (recomputed === row.predictedSetScore) {
      console.error(`STOP: #${row.id} recomputed value "${recomputed}" is identical to the stored value -- this row wasn't actually broken; re-check the approved ID list.`);
      process.exit(1);
    }

    const graded = row.actualWinnerId !== null || row.resolvedAt !== null;
    plan.push({ id: row.id, before: row.predictedSetScore, after: recomputed, graded, row });
  }

  console.log(`\nNo drift detected. Plan (${plan.length} rows):`);
  for (const p of plan) {
    console.log(`  #${p.id}: "${p.before}" -> "${p.after}" (graded=${p.graded})`);
  }

  // Fresh backup of full row state before any write.
  const backupDir = path.join(__dirname, "..", "..", "backups");
  fs.mkdirSync(backupDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = path.join(backupDir, `set-score-backfill-${plan.length}rows-${stamp}.json`);
  fs.writeFileSync(backupPath, JSON.stringify(rows, null, 2));
  console.log(`\nBackup of pre-backfill row state (all columns, ${plan.length} rows) written to: ${backupPath}`);

  if (dryRun) {
    console.log(`\nDRY RUN -- no writes performed. Re-run with --apply to write.`);
    await pool.end();
    return;
  }

  console.log(`\nApplying updates...`);
  const appliedAt = new Date().toISOString();
  for (const p of plan) {
    const engine = p.row.engine as EngineBreakdown & Record<string, unknown>;
    const newEngine: Record<string, unknown> = {
      ...engine,
      setScoreBackfillCorrected: true,
      setScoreBackfillPreviousValue: p.before,
      setScoreBackfillAppliedAt: appliedAt,
      setScoreBackfillWasGradedAtCorrection: p.graded,
      setScoreBackfillReason:
        "Corrected the pre-2026-07-13 predictSetScore bug (predictionEngine/index.ts) that swapped which literal came first whenever player 2 was the predicted winner, making the winner appear to trail their own predicted set score. This is a retroactive label correction of a stored display value, not a newly-generated prediction -- the underlying calibratedProbability/predictedWinnerId are untouched.",
    };
    await db.update(predictionsTable).set({ predictedSetScore: p.after, engine: newEngine }).where(eq(predictionsTable.id, p.id));
    console.log(`  Updated #${p.id}: "${p.before}" -> "${p.after}" (backfill flag set, graded-at-correction=${p.graded})`);
  }

  console.log(`\nDone. ${plan.length} rows updated.`);
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
